import type { RoleDefinition } from "../shared/types.js";

export const WEREWOLF_ROLE_DEFINITIONS = {
  ordinary_villager: {
    id: "ordinary_villager",
    gameId: "werewolves",
    nameBg: "Селянин / Селянка",
    shortDescriptionBg: "Няма нощно действие. Печели, като помогне на селото да разкрие заплахата.",
    fullDescriptionBg:
      "Нямаш тайна сила, но имаш най-важното оръжие на масата: памет. Слушаш кой сменя историята си, кой мълчи твърде удобно и кой тласка селото към грешен глас. Побеждаваш, когато последната нощна заплаха бъде извадена от играта.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 24,
    dependencies: [],
    assetKey: "ordinary-villager",
    tags: ["основна", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  healer: {
    id: "healer",
    gameId: "werewolves",
    nameBg: "Лечител",
    shortDescriptionBg: "Всяка нощ пази един друг играч от атаката на Върколаците или Вампирите.",
    fullDescriptionBg:
      "Всяка нощ избираш един друг жив играч и оставяш защита пред вратата му. Ако заплахата посегне точно там, сутринта селото се събужда без жертва. Не можеш да пазиш себе си и не можеш да пазиш един и същ човек две нощи поред, затова изборът ти трябва да има ритъм.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "healer",
    tags: ["основна", "нощна роля", "защитна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  witch: {
    id: "witch",
    gameId: "werewolves",
    nameBg: "Вещица",
    shortDescriptionBg: "Има една лечебна и една отровна отвара, всяка по веднъж за цялата игра.",
    fullDescriptionBg:
      "Нощта ти казва кой е нарочен за смърт, но не ти казва дали си права да го спасиш. Имаш една лечебна отвара и една отрова за цялата игра; можеш да използваш и двете в една нощ, ако моментът го изисква. Вещицата печели не с бързина, а с търпение.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: true,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "witch",
    tags: ["основна", "нощна роля", "защитна", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  seer: {
    id: "seer",
    gameId: "werewolves",
    nameBg: "Гадателка",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Картите не говорят силно, но говорят вярно. Всяка нощ посочваш един играч и научаваш дали принадлежи към активната заплаха: Върколак, Вампир или невинен спрямо този вариант. През деня информацията ти тежи само ако я подадеш така, че селото да не те изгори веднага.",
    team: "village",
    value: 7,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "seer",
    tags: ["основна", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  hunter: {
    id: "hunter",
    gameId: "werewolves",
    nameBg: "Ловец",
    shortDescriptionBg: "Когато умре, веднага може да застреля друг играч.",
    fullDescriptionBg:
      "Когато паднеш, масата замлъква за последния ти избор. Посочваш един жив играч без нов спор и той напуска играта заедно с теб. Добър Ловец събира подозренията си преди смъртта, защото последният изстрел не търпи колебание.",
    team: "village",
    value: 3,
    nightOrder: 12,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "hunter",
    tags: ["основна", "атакуваща", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  red_riding_hood: {
    id: "red_riding_hood",
    gameId: "werewolves",
    nameBg: "Червена шапчица",
    shortDescriptionBg: "Докато Ловецът е жив, не умира от атака на Върколаци или Вампири.",
    fullDescriptionBg:
      "Докато Ловецът още диша, гората сякаш отказва да те погълне. Фракционната нощна атака не те убива, но дневното гласуване и други ефекти все още могат да те извадят от играта. Ако Ловецът падне, и твоята невидима закрила пада с него.",
    team: "village",
    value: 3,
    nightOrder: 13,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [{ roleId: "hunter", reasonBg: "Червена шапчица се използва само когато Ловецът е в играта." }],
    assetKey: "red-riding-hood",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cupid: {
    id: "cupid",
    gameId: "werewolves",
    nameBg: "Купидон",
    shortDescriptionBg: "Първата нощ избира двама Влюбени. Смъртта на единия повлича другия.",
    fullDescriptionBg:
      "Първата нощ стреляш само веднъж, но стрелата остава до края. Свързваш двама играчи: ако единият умре, другият не издържа след него. Ако любовта пресече вражески отбори, двамата могат да се превърнат в собствена малка фракция срещу всички.",
    team: "village",
    value: -2,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cupid",
    tags: ["разширена", "нощна роля", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
    winConditionBg: "Обичайно печели със селото, но може да създаде отделна победа за Влюбените.",
  },
  mayor: {
    id: "mayor",
    gameId: "werewolves",
    nameBg: "Кмет",
    shortDescriptionBg: "При равенство в откритото гласуване гласът му решава изхода.",
    fullDescriptionBg:
      "Носиш печата на селото, но той не е постоянна бухалка. При равенство твоят глас решава накъде се накланя присъдата. Ако Кметът е публична титла и умре, селото трябва да получи наследник, иначе властта остава висяща.",
    team: "village",
    value: 2,
    nightOrder: 15,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  oracle: {
    id: "oracle",
    gameId: "werewolves",
    nameBg: "Оракул",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Оракулът не гадае по шумовете, а по знаците между тях. Всяка нощ посочваш играч и научаваш дали той е част от активната нощна заплаха. Това е силна истина, но истината оцелява само ако я внесеш в разговора внимателно.",
    team: "village",
    value: 7,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "oracle",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  priest: {
    id: "priest",
    gameId: "werewolves",
    nameBg: "Свещеник",
    shortDescriptionBg: "Веднъж благославя играч, който остава защитен от нощна смърт.",
    fullDescriptionBg:
      "Имаш една благословия и тя не е за показ. Избираш играч веднъж за цялата игра, а защитата остава върху него до края и спира нощни убийства, включително атака, отрова, лов и ковашки меч. Трудното е да решиш кой ще бъде важен утре, не кой изглежда важен тази нощ.",
    team: "village",
    value: 3,
    nightOrder: 2,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [
      { roleId: "blacksmith", reasonBg: "Свещеникът се препоръчва само когато Ковачът е в играта." },
      { roleId: "vampire_hunter", reasonBg: "Свещеникът се препоръчва само когато Убиецът на вампири е в играта." },
      { roleId: "witch", reasonBg: "Свещеникът се препоръчва само когато Вещицата е в играта." },
    ],
    assetKey: "priest",
    tags: ["разширена", "нощна роля", "защитна", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cook: {
    id: "cook",
    gameId: "werewolves",
    nameBg: "Готвач",
    shortDescriptionBg: "Не умира от атака на Върколаци или ухапване на Вампири.",
    fullDescriptionBg:
      "Нощта идва до кухнята и си тръгва гладна. Ако фракционната атака избере теб, оцеляваш, а Разказвачът обявява само, че няма жертва от тази атака. Ролята ти работи най-добре, когато никой не разбира защо сутринта е тиха.",
    team: "village",
    value: 4,
    nightOrder: 14,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cook",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  blacksmith: {
    id: "blacksmith",
    gameId: "werewolves",
    nameBg: "Ковач",
    shortDescriptionBg: "Веднъж изковава меч за друг играч, който го използва веднага.",
    fullDescriptionBg:
      "Веднъж през играта изваждаш меч от огъня и го даваш на друг играч. В дигиталния режим изборът се случва наведнъж: кой получава меча и срещу кого го насочва. Смъртта идва в началото на следващия ден, затова ударът трябва да е повече доказателство, отколкото гняв.",
    team: "village",
    value: 2,
    nightOrder: 11,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "blacksmith",
    tags: ["разширена", "нощна роля", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  insomniac: {
    id: "insomniac",
    gameId: "werewolves",
    nameBg: "Неспяща",
    shortDescriptionBg: "В края на всяка нощ научава дали някой от двамата съседни живи играчи е бил активен.",
    fullDescriptionBg:
      "Ти не спиш, но и не виждаш всичко. В края на нощта разбираш дали някой от двамата ти живи съседи е бил активен, без да научаваш кой точно и какво е направил. Това е следа, не присъда: силна е само когато я вържеш с дневното поведение.",
    team: "village",
    value: 3,
    nightOrder: 16,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "insomniac",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  vampire_hunter: {
    id: "vampire_hunter",
    gameId: "werewolves",
    nameBg: "Убиец на вампири",
    shortDescriptionBg: "Всяка нощ може да ловува. Ако убие невинен, губи умението си.",
    fullDescriptionBg:
      "Всяка нощ можеш да излезеш на лов и да посочиш жертва. Ако удариш Върколак или Вампир, селото получава шанс; ако удариш невинен, оръжието ти замлъква до края. Това е роля за студена глава, не за шумни обвинения.",
    team: "village",
    value: 3,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vampire-hunter",
    tags: ["разширена", "нощна роля", "атакуваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  investigator: {
    id: "investigator",
    gameId: "werewolves",
    nameBg: "Следователка",
    shortDescriptionBg: "Веднъж проверява група от трима съседни живи играчи за Върколак или Вампир.",
    fullDescriptionBg:
      "Веднъж за играта ограждаш три съседни живи места и търсиш следа от нощната заплаха. Получаваш само отговор дали вътре има Върколак или Вампир, не колко са и не кои са. Следователката печели време, когато зададе правилната група в правилния ден.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "investigator",
    tags: ["разширена", "нощна роля", "разследваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  werewolf: {
    id: "werewolf",
    gameId: "werewolves",
    nameBg: "Върколак",
    shortDescriptionBg: "Всяка нощ се буди с другите Върколаци и избира жертва.",
    fullDescriptionBg:
      "Вие се познавате в тъмното и се преструвате на непознати през деня. Всяка нощ избирате жертва за фракционната атака; ако не стигнете до съгласие, нощта може да остане без ваша смърт. Добър Върколак не просто убива, а оставя селото да спори в грешната посока.",
    team: "werewolves",
    value: -6,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 6,
    dependencies: [],
    assetKey: "werewolf",
    tags: ["основна", "нощна роля", "атакуваща", "върколаци"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  vampire: {
    id: "vampire",
    gameId: "werewolves",
    nameBg: "Вампир",
    shortDescriptionBg: "Всяка нощ се буди с другите Вампири и избира жертва, която умира в края на деня.",
    fullDescriptionBg:
      "Вампирската атака е тиха и закъснява като лоша новина. Жертвата не пада веднага, а умира в края на следващия дневен цикъл, което прави обвиненията по-мътни. Можете да замените Върколаците или да играете като трети отбор, когато масата е готова за по-сложна война.",
    team: "vampires",
    value: -6,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 6,
    dependencies: [],
    assetKey: "vampire",
    tags: ["разширена", "нощна роля", "атакуваща", "вампири"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  drunk: {
    id: "drunk",
    gameId: "werewolves",
    nameBg: "Пияница",
    shortDescriptionBg: "Разбира истинската си роля едва в началото на втората нощ.",
    fullDescriptionBg:
      "Започваш играта с мъгла в главата и без истинската си карта. В началото на втората нощ получаваш ролята, която Разказвачът е пазил за теб, и от този момент играеш с новата си съдба. Подходящо е за групи, които обичат контролирания хаос.",
    team: "neutral",
    value: -2,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "drunk",
    tags: ["разширена", "нощна роля", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  stray_cat: {
    id: "stray_cat",
    gameId: "werewolves",
    nameBg: "Улична котка",
    shortDescriptionBg: "Промо роля, която всяка нощ сменя условния си собственик.",
    fullDescriptionBg:
      "Котката избира къде да пренощува, а селото никога не е напълно сигурно при кого е била. Всяка нощ посочваш нов дом; ако попаднеш при Върколак или Вампир, и двамата излизате от играта. Това е промо роля с висок риск и много памет по масата.",
    team: "village",
    value: 6,
    nightOrder: -1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "stray-cat",
    tags: ["промо", "разширена", "нощна роля", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  guard_dog: {
    id: "guard_dog",
    gameId: "werewolves",
    nameBg: "Куче пазач",
    shortDescriptionBg: "Промо публична карта, която пази публично избрания Кмет от дневно елиминиране.",
    fullDescriptionBg:
      "Кучето пазач стои до публичния Кмет и прави дневното елиминиране по-трудно. Докато е живо, Кметът не може да бъде изваден чрез гласуване, но самото куче може да бъде цел. Работи само когато Кметът е открита допълнителна карта, не просто тайна роля.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [{ roleId: "mayor", reasonBg: "Куче пазач изисква публично избран Кмет." }],
    assetKey: "guard-dog",
    tags: ["промо", "разширена", "публична", "защитна", "селяни"],
    secret: false,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  thief: {
    id: "thief",
    gameId: "werewolves",
    nameBg: "Крадец",
    shortDescriptionBg: "Веднъж краде карта: става новата роля, а целта става Селянин.",
    fullDescriptionBg:
      "Крадецът е роля за маси, които искат една нощ да обърне всички планове. Веднъж избираш играч, вземаш ролята му, а той става Селянин. Заради силния ефект остава ръчна разширена опция, не част от стандартните автоматични раздавания.",
    team: "neutral",
    value: 0,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 13,
    maxCopies: 1,
    dependencies: [],
    assetKey: "thief",
    tags: ["разширена", "нощна роля", "неутрална", "еднократна"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  little_girl: {
    id: "little_girl",
    gameId: "werewolves",
    nameBg: "Малко момиче",
    shortDescriptionBg: "Разширена ръчна роля за игра на живо с надничане по време на нощта.",
    fullDescriptionBg:
      "Малкото момиче е роля за групи, които я играят физически с Разказвач и много доверие около масата. В дигитален режим не се превежда чисто към телефонен интерфейс, затова остава ръчна advanced опция. Ако я включите, водещият трябва ясно да обясни как ще се играе.",
    team: "village",
    value: 0,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "little-girl",
    tags: ["разширена", "селяни"],
    secret: true,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
} as const satisfies Record<string, RoleDefinition>;
