import type { RoleDefinition } from "../shared/types.js";

export const WEREWOLF_ROLE_DEFINITIONS = {
  ordinary_villager: {
    id: "ordinary_villager",
    gameId: "werewolves",
    nameBg: "Селянин / Селянка",
    shortDescriptionBg: "Няма нощно действие. Печели, като помогне на селото да разкрие заплахата.",
    fullDescriptionBg:
      "Селяните обсъждат през деня, номинират подозрителни играчи и гласуват за елиминиране. Те печелят, когато последният Върколак или Вампир бъде премахнат.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 24,
    dependencies: [],
    assetKey: "ordinary-villager",
    tags: ["основна", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  healer: {
    id: "healer",
    gameId: "werewolves",
    nameBg: "Лечител",
    shortDescriptionBg: "Всяка нощ пази един друг играч от атаката на Върколаците или Вампирите.",
    fullDescriptionBg:
      "Лечителят избира един друг жив играч всяка нощ. Ако този играч е жертвата на Върколаците или Вампирите, не умира. По PDF правилата Лечителят не лекува себе си и не може да избере същия играч две поредни нощи.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "healer",
    tags: ["основна", "нощна роля", "защитна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  witch: {
    id: "witch",
    gameId: "werewolves",
    nameBg: "Вещица",
    shortDescriptionBg: "Има една лечебна и една отровна отвара, всяка по веднъж за цялата игра.",
    fullDescriptionBg:
      "Всяка нощ вижда жертвата на Върколаците или Вампирите. Може веднъж да я спаси с лечебна отвара и веднъж да отрови друг играч. Двете отвари могат да се използват в една и съща нощ.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: true,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "witch",
    tags: ["основна", "нощна роля", "защитна", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  seer: {
    id: "seer",
    gameId: "werewolves",
    nameBg: "Гадателка",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Гадателката посочва един играч по време на нощната фаза и получава отговор дали този играч е от заплахата в текущия вариант: Върколак, Вампир или не.",
    team: "village",
    value: 7,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "seer",
    tags: ["основна", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  hunter: {
    id: "hunter",
    gameId: "werewolves",
    nameBg: "Ловец",
    shortDescriptionBg: "Когато умре, веднага може да застреля друг играч.",
    fullDescriptionBg:
      "При обявяване на смъртта си Ловецът избира един жив играч без обсъждане. Избраният играч също напуска играта.",
    team: "village",
    value: 3,
    nightOrder: 12,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "hunter",
    tags: ["основна", "атакуваща", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  red_riding_hood: {
    id: "red_riding_hood",
    gameId: "werewolves",
    nameBg: "Червена шапчица",
    shortDescriptionBg: "Докато Ловецът е жив, не умира от атака на Върколаци или Вампири.",
    fullDescriptionBg:
      "Червената шапчица е защитена от фракционната нощна атака, докато Ловецът е жив. Може да умре от други ефекти или чрез дневно гласуване.",
    team: "village",
    value: 3,
    nightOrder: 13,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [{ roleId: "hunter", reasonBg: "Червена шапчица се използва само когато Ловецът е в играта." }],
    assetKey: "red-riding-hood",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cupid: {
    id: "cupid",
    gameId: "werewolves",
    nameBg: "Купидон",
    shortDescriptionBg: "Първата нощ избира двама Влюбени. Смъртта на единия повлича другия.",
    fullDescriptionBg:
      "Купидон се буди само през първата нощ и свързва двама играчи. Ако Влюбените са от различни отбори, те могат да играят за собствена победа като последните оцелели.",
    team: "village",
    value: -2,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cupid",
    tags: ["разширена", "нощна роля", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
    winConditionBg: "Обичайно печели със селото, но може да създаде отделна победа за Влюбените.",
  },
  mayor: {
    id: "mayor",
    gameId: "werewolves",
    nameBg: "Кмет",
    shortDescriptionBg: "При равенство в откритото гласуване гласът му решава изхода.",
    fullDescriptionBg:
      "Кметът може да бъде тайна роля или публична допълнителна карта, избрана чрез открито гласуване. Ако публичният Кмет умре, предава титлата на друг жив играч.",
    team: "village",
    value: 2,
    nightOrder: 15,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  oracle: {
    id: "oracle",
    gameId: "werewolves",
    nameBg: "Оракул",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Оракулът изпълнява силна разследваща роля. По време на нощта посочва един играч и разбира дали той принадлежи към активната заплаха.",
    team: "village",
    value: 7,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "oracle",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  priest: {
    id: "priest",
    gameId: "werewolves",
    nameBg: "Свещеник",
    shortDescriptionBg: "Веднъж благославя играч, който остава защитен от нощна смърт.",
    fullDescriptionBg:
      "Свещеникът може веднъж за цялата игра да благослови един играч. Благословията остава до края и игнорира нощни убийства, включително атака, отрова, лов и ковашки меч.",
    team: "village",
    value: 3,
    nightOrder: 2,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [
      { roleId: "blacksmith", reasonBg: "Свещеникът се препоръчва само когато Ковачът е в играта." },
      { roleId: "vampire_hunter", reasonBg: "Свещеникът се препоръчва само когато Убиецът на вампири е в играта." },
      { roleId: "witch", reasonBg: "Свещеникът се препоръчва само когато Вещицата е в играта." },
    ],
    assetKey: "priest",
    tags: ["разширена", "нощна роля", "защитна", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cook: {
    id: "cook",
    gameId: "werewolves",
    nameBg: "Готвач",
    shortDescriptionBg: "Не умира от атака на Върколаци или ухапване на Вампири.",
    fullDescriptionBg:
      "Ако фракционната нощна атака избере Готвача, той оцелява. Модераторът обявява, че няма жертва от тази атака, без да разкрива кой е Готвачът.",
    team: "village",
    value: 4,
    nightOrder: 14,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cook",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  blacksmith: {
    id: "blacksmith",
    gameId: "werewolves",
    nameBg: "Ковач",
    shortDescriptionBg: "Веднъж изковава меч за друг играч, който го използва веднага.",
    fullDescriptionBg:
      "Ковачът може веднъж през нощта да даде меч на друг играч. Получилият меч посочва жертва, която умира в началото на следващия ден.",
    team: "village",
    value: 2,
    nightOrder: 11,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "blacksmith",
    tags: ["разширена", "нощна роля", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  insomniac: {
    id: "insomniac",
    gameId: "werewolves",
    nameBg: "Неспяща",
    shortDescriptionBg: "В края на всяка нощ научава дали някой от двамата съседни живи играчи е бил активен.",
    fullDescriptionBg:
      "Неспящата получава информация за активност около себе си, но не научава кой точно е действал и не научава какво действие е извършено.",
    team: "village",
    value: 3,
    nightOrder: 16,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "insomniac",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  vampire_hunter: {
    id: "vampire_hunter",
    gameId: "werewolves",
    nameBg: "Убиец на вампири",
    shortDescriptionBg: "Всяка нощ може да ловува. Ако убие невинен, губи умението си.",
    fullDescriptionBg:
      "Убиецът на вампири може да посочи един играч за нощна смърт. Ако жертвата не е Върколак или Вампир, умението се губи до края на играта.",
    team: "village",
    value: 3,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vampire-hunter",
    tags: ["разширена", "нощна роля", "атакуваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  investigator: {
    id: "investigator",
    gameId: "werewolves",
    nameBg: "Следователка",
    shortDescriptionBg: "Веднъж проверява група от трима съседни живи играчи за Върколак или Вампир.",
    fullDescriptionBg:
      "Следователката избира три живи съседни места и разбира дали поне един от тях е Върколак или Вампир. Не научава колко са и кои са.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "investigator",
    tags: ["разширена", "нощна роля", "разследваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  werewolf: {
    id: "werewolf",
    gameId: "werewolves",
    nameBg: "Върколак",
    shortDescriptionBg: "Всяка нощ се буди с другите Върколаци и избира жертва.",
    fullDescriptionBg:
      "Върколаците познават съотборниците си и всяка нощ се опитват да изберат една жертва. Ако не постигнат съгласие, няма нощна жертва от тях.",
    team: "werewolves",
    value: -6,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 6,
    dependencies: [],
    assetKey: "werewolf",
    tags: ["основна", "нощна роля", "атакуваща", "върколаци"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  vampire: {
    id: "vampire",
    gameId: "werewolves",
    nameBg: "Вампир",
    shortDescriptionBg: "Всяка нощ се буди с другите Вампири и избира жертва, която умира в края на деня.",
    fullDescriptionBg:
      "Вампирите могат да заменят Върколаците или да бъдат трети отбор. Ухапаният играч не разбира веднага и умира в края на следващата дневна фаза.",
    team: "vampires",
    value: -6,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 6,
    dependencies: [],
    assetKey: "vampire",
    tags: ["разширена", "нощна роля", "атакуваща", "вампири"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  drunk: {
    id: "drunk",
    gameId: "werewolves",
    nameBg: "Пияница",
    shortDescriptionBg: "Разбира истинската си роля едва в началото на втората нощ.",
    fullDescriptionBg:
      "Пияницата започва без да знае какъв персонаж ще играе. Модераторът пази допълнителна карта и я разкрива на Пияницата през втората нощ.",
    team: "neutral",
    value: -2,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "drunk",
    tags: ["разширена", "нощна роля", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  stray_cat: {
    id: "stray_cat",
    gameId: "werewolves",
    nameBg: "Улична котка",
    shortDescriptionBg: "Промо роля, която всяка нощ сменя условния си собственик.",
    fullDescriptionBg:
      "Уличната котка се буди първа всяка нощ и избира нов собственик. Ако попадне при Върколак или Вампир, и котката, и този играч излизат от играта.",
    team: "village",
    value: 6,
    nightOrder: -1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "stray-cat",
    tags: ["промо", "разширена", "нощна роля", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  guard_dog: {
    id: "guard_dog",
    gameId: "werewolves",
    nameBg: "Куче пазач",
    shortDescriptionBg: "Промо публична карта, която пази публично избрания Кмет от дневно елиминиране.",
    fullDescriptionBg:
      "Кучето пазач се използва само когато Кметът е публична допълнителна карта. Докато е живо, Кметът не може да бъде линчуван, но самото куче може да бъде цел на действия.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [{ roleId: "mayor", reasonBg: "Куче пазач изисква публично избран Кмет." }],
    assetKey: "guard-dog",
    tags: ["промо", "разширена", "публична", "защитна", "селяни"],
    secret: false,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  thief: {
    id: "thief",
    gameId: "werewolves",
    nameBg: "Крадец",
    shortDescriptionBg: "Веднъж краде карта: става новата роля, а целта става Селянин.",
    fullDescriptionBg:
      "Дигитална разширена роля за групи, които искат повече хаос. Крадецът избира играч, взема ролята му, а избраният играч става Селянин.",
    team: "neutral",
    value: 0,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 13,
    maxCopies: 1,
    dependencies: [],
    assetKey: "thief",
    tags: ["разширена", "нощна роля", "неутрална", "еднократна"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  little_girl: {
    id: "little_girl",
    gameId: "werewolves",
    nameBg: "Малко момиче",
    shortDescriptionBg: "Разширена ръчна роля за игра на живо с надничане по време на нощта.",
    fullDescriptionBg:
      "Малкото момиче е legacy/advanced опция за групи, които я играят на живо. В дигитален режим е маркирана с предупреждение, защото не се адаптира чисто към телефонен UI.",
    team: "village",
    value: 0,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "little-girl",
    tags: ["разширена", "селяни"],
    secret: true,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
} as const satisfies Record<string, RoleDefinition>;
