import type { RoleDefinition } from "../shared/types.js";

export const WEREWOLF_ROLE_DEFINITIONS = {
  ordinary_villager: {
    id: "ordinary_villager",
    gameId: "werewolves",
    nameBg: "Селянин / Селянка",
    shortDescriptionBg: "Няма нощно действие. Печели, като помогне на селото да разкрие заплахата.",
    fullDescriptionBg:
      "Нямаш тайна сила, но имаш най-важното оръжие на масата: памет. Слушаш кой сменя историята си, кой мълчи твърде удобно и кой тласка селото към грешен глас. Побеждаваш, когато последната нощна заплаха бъде извадена от играта.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 24,
    dependencies: [],
    assetKey: "ordinary-villager",
    tags: ["основна", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  healer: {
    id: "healer",
    gameId: "werewolves",
    nameBg: "Лечител",
    shortDescriptionBg: "Всяка нощ пази един друг играч от нощна смърт.",
    fullDescriptionBg:
      "Всяка нощ избираш един друг жив играч. Ако тази нощ той трябва да умре, защитата ти го спасява. Не можеш да пазиш себе си или един и същ човек две нощи поред, затова трябва да предвидиш следващата атака.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "healer",
    tags: ["основна", "нощна роля", "защитна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  witch: {
    id: "witch",
    gameId: "werewolves",
    nameBg: "Вещица",
    shortDescriptionBg: "Има една лечебна и една отровна отвара, всяка по веднъж за цялата игра.",
    fullDescriptionBg:
      "Нощта ти показва кой е нарочен за смърт, но решението остава твое. Имаш една лечебна отвара и една отрова за цялата игра; можеш да използваш и двете в една нощ. Ако ги похарчиш рано, после оставаш само с гласа си.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: true,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "witch",
    tags: ["основна", "нощна роля", "защитна", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  seer: {
    id: "seer",
    gameId: "werewolves",
    nameBg: "Гадателка",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Всяка нощ посочваш един играч и научаваш дали е Върколак или Вампир. Не виждаш точната му роля, когато не е заплаха. През деня трябва да използваш наученото, без да разкриеш твърде рано коя си.",
    team: "village",
    value: 7,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "seer",
    tags: ["основна", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  hunter: {
    id: "hunter",
    gameId: "werewolves",
    nameBg: "Ловец",
    shortDescriptionBg: "Когато умре, веднага може да застреля друг играч.",
    fullDescriptionBg:
      "Когато паднеш, избираш един жив играч и го вземаш със себе си. Няма ново обсъждане преди изстрела, затова следи подозренията си още докато си в играта.",
    team: "village",
    value: 3,
    nightOrder: 12,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "hunter",
    tags: ["основна", "атакуваща", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  red_riding_hood: {
    id: "red_riding_hood",
    gameId: "werewolves",
    nameBg: "Червена шапчица",
    shortDescriptionBg: "Докато Ловецът е жив, не умира от атака на Върколаци или Вампири.",
    fullDescriptionBg:
      "Докато Ловецът е жив, атака от Върколаци или Вампири не те убива. Дневното гласуване и останалите нощни ефекти все още могат да те извадят от играта. Ако Ловецът падне, защитата ти изчезва.",
    team: "village",
    value: 3,
    nightOrder: 13,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [{ roleId: "hunter", reasonBg: "Червена шапчица се използва само когато Ловецът е в играта." }],
    assetKey: "red-riding-hood",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cupid: {
    id: "cupid",
    gameId: "werewolves",
    nameBg: "Купидон",
    shortDescriptionBg: "Първата нощ избира двама Влюбени. Смъртта на единия повлича другия.",
    fullDescriptionBg:
      "Първата нощ стреляш само веднъж, но стрелата остава до края. Свързваш двама играчи: ако единият умре, другият не издържа след него. Ако любовта пресече вражески отбори, двамата могат да се превърнат в собствена малка фракция срещу всички.",
    team: "village",
    value: -2,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cupid",
    tags: ["разширена", "нощна роля", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
    winConditionBg: "Обичайно печели със селото, но може да създаде отделна победа за Влюбените.",
  },
  mayor: {
    id: "mayor",
    gameId: "werewolves",
    nameBg: "Кмет",
    shortDescriptionBg: "При равенство в откритото гласуване гласът му решава изхода.",
    fullDescriptionBg:
      "При равенство твоят глас решава кой напуска играта. Ако титлата е публична и умреш, селото избира наследник. В останалото гласът ти тежи колкото всеки друг.",
    team: "village",
    value: 2,
    nightOrder: 15,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "селяни"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["werewolves"],
  },
  oracle: {
    id: "oracle",
    gameId: "werewolves",
    nameBg: "Оракул",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е Върколак или Вампир.",
    fullDescriptionBg:
      "Всяка нощ посочваш играч и научаваш дали е част от активната нощна заплаха. Отговорът е точен, но не разкрива коя роля стои зад него. Подай информацията внимателно, за да не станеш следващата жертва.",
    team: "village",
    value: 7,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "oracle",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  priest: {
    id: "priest",
    gameId: "werewolves",
    nameBg: "Свещеник",
    shortDescriptionBg: "Веднъж благославя играч, който остава защитен от нощна смърт.",
    fullDescriptionBg:
      "Веднъж за цялата игра благославяш друг играч. Защитата остава до края и спира нощна смърт от атака, отрова, лов или ковашки меч. Избери човек, който ще бъде важен и през следващите дни.",
    team: "village",
    value: 3,
    nightOrder: 2,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [
      { roleId: "blacksmith", reasonBg: "Свещеникът се препоръчва само когато Ковачът е в играта." },
      { roleId: "vampire_hunter", reasonBg: "Свещеникът се препоръчва само когато Убиецът на вампири е в играта." },
      { roleId: "witch", reasonBg: "Свещеникът се препоръчва само когато Вещицата е в играта." },
    ],
    assetKey: "priest",
    tags: ["разширена", "нощна роля", "защитна", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  cook: {
    id: "cook",
    gameId: "werewolves",
    nameBg: "Готвач",
    shortDescriptionBg: "Не умира от атака на Върколаци или ухапване на Вампири.",
    fullDescriptionBg:
      "Ако Върколаците или Вампирите изберат теб, оцеляваш. Разказвачът обявява само, че от тази атака няма жертва, без да разкрива защо. Други нощни ефекти и дневното гласуване все още могат да те извадят от играта.",
    team: "village",
    value: 4,
    nightOrder: 14,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "cook",
    tags: ["разширена", "защитна", "селяни"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  blacksmith: {
    id: "blacksmith",
    gameId: "werewolves",
    nameBg: "Ковач",
    shortDescriptionBg: "Веднъж изковава меч за друг играч, който го използва веднага.",
    fullDescriptionBg:
      "Веднъж през играта даваш меч на друг играч и едновременно избираш срещу кого да бъде използван. Ударът се изпълнява през нощта, а резултатът се вижда на следващия ден. Мечът не може да бъде върнат, затова не бързай с избора.",
    team: "village",
    value: 2,
    nightOrder: 11,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "blacksmith",
    tags: ["разширена", "нощна роля", "атакуваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  insomniac: {
    id: "insomniac",
    gameId: "werewolves",
    nameBg: "Неспяща",
    shortDescriptionBg: "В края на всяка нощ научава дали някой от двамата съседни живи играчи е бил активен.",
    fullDescriptionBg:
      "Ти не спиш, но и не виждаш всичко. В края на нощта разбираш дали някой от двамата ти живи съседи е бил активен, без да научаваш кой точно и какво е направил. Това е следа, не присъда: силна е само когато я вържеш с дневното поведение.",
    team: "village",
    value: 3,
    nightOrder: 16,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "insomniac",
    tags: ["разширена", "нощна роля", "разследваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  vampire_hunter: {
    id: "vampire_hunter",
    gameId: "werewolves",
    nameBg: "Убиец на вампири",
    shortDescriptionBg: "Всяка нощ може да ловува. Ако убие невинен, губи умението си.",
    fullDescriptionBg:
      "Всяка нощ можеш да излезеш на лов и да посочиш жертва. Ако удариш Върколак или Вампир, селото получава шанс; ако удариш невинен, оръжието ти замлъква до края. Това е роля за студена глава, не за шумни обвинения.",
    team: "village",
    value: 3,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vampire-hunter",
    tags: ["разширена", "нощна роля", "атакуваща", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  investigator: {
    id: "investigator",
    gameId: "werewolves",
    nameBg: "Следователка",
    shortDescriptionBg: "Веднъж проверява група от трима съседни живи играчи за Върколак или Вампир.",
    fullDescriptionBg:
      "Веднъж за цялата игра проверяваш три съседни живи места. Научаваш дали сред тях има Върколак или Вампир, но не колко са и не кой е виновният. Избери тройка, която ще ти помогне да разделиш реални подозрения.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "investigator",
    tags: ["разширена", "нощна роля", "разследваща", "еднократна", "селяни"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  werewolf: {
    id: "werewolf",
    gameId: "werewolves",
    nameBg: "Върколак",
    shortDescriptionBg: "Всяка нощ се буди с другите Върколаци и избира жертва.",
    fullDescriptionBg:
      "Познавате се в тъмното и се преструвате на непознати през деня. Всяка нощ трябва да посочите една и съща жертва; без съгласие няма атака. През деня печелите време, като насочвате подозренията далеч от своята глутница.",
    team: "werewolves",
    value: -6,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 7,
    dependencies: [],
    assetKey: "werewolf",
    tags: ["основна", "нощна роля", "атакуваща", "върколаци"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["werewolves"],
  },
  vampire: {
    id: "vampire",
    gameId: "werewolves",
    nameBg: "Вампир",
    shortDescriptionBg: "Всяка нощ се буди с другите Вампири и избира жертва, която умира в края на деня.",
    fullDescriptionBg:
      "Вампирската атака е тиха и закъснява като лоша новина. Жертвата не пада веднага, а умира в края на следващия дневен цикъл, което прави обвиненията по-мътни. Можете да замените Върколаците или да играете като трети отбор, когато масата е готова за по-сложна война.",
    team: "vampires",
    value: -6,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 12,
    maxCopies: 6,
    dependencies: [],
    assetKey: "vampire",
    tags: ["разширена", "нощна роля", "атакуваща", "вампири"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  drunk: {
    id: "drunk",
    gameId: "werewolves",
    nameBg: "Пияница",
    shortDescriptionBg: "Разбира истинската си роля едва в началото на втората нощ.",
    fullDescriptionBg:
      "Започваш без да знаеш истинската си роля. В началото на втората нощ получаваш картата, която е била запазена за теб, и от този момент играеш с нейния отбор и способности.",
    team: "neutral",
    value: -2,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "drunk",
    tags: ["разширена", "нощна роля", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  stray_cat: {
    id: "stray_cat",
    gameId: "werewolves",
    nameBg: "Улична котка",
    shortDescriptionBg: "Настолна карта за ръчно водене, която всяка нощ избира нов дом.",
    fullDescriptionBg:
      "Котката стои като открита карта в средата на масата и всяка нощ условно отива при нов собственик. Ако попадне при Върколак или Вампир, чудовището и котката излизат от играта. Понеже настолната версия движи публична карта между играчите, използвай я най-вече с човешки Разказвач.",
    team: "village",
    value: 6,
    nightOrder: -1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "stray-cat",
    tags: ["настолна", "разширена", "нощна роля", "селяни"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  guard_dog: {
    id: "guard_dog",
    gameId: "werewolves",
    nameBg: "Куче пазач",
    shortDescriptionBg: "Настолна публична карта за ръчно водене, която пази избрания Кмет от дневна елиминация.",
    fullDescriptionBg:
      "Кучето пазач стои до публично избрания Кмет и спира дневното му елиминиране, докато самото куче е живо. В настолните правила кучето е отделна открита карта, която може да бъде нападана, линчувана, убивана или спасявана като отделна цел. Затова го използвай най-вече с човешки Разказвач и публичен Кмет.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [{ roleId: "mayor", reasonBg: "Куче пазач изисква публично избран Кмет." }],
    assetKey: "guard-dog",
    tags: ["настолна", "разширена", "публична", "защитна", "селяни"],
    secret: false,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  thief: {
    id: "thief",
    gameId: "werewolves",
    nameBg: "Крадец",
    shortDescriptionBg: "Веднъж краде карта: става новата роля, а целта става Селянин.",
    fullDescriptionBg:
      "Крадецът е роля за маси, които искат първата нощ да обърне всички планове. Веднъж избираш играч, вземаш ролята му, а той става Селянин. От този момент играеш с новата си роля и нейния отбор.",
    team: "neutral",
    value: 0,
    nightOrder: 0,
    isDefaultEnabled: false,
    minPlayers: 13,
    maxCopies: 1,
    dependencies: [],
    assetKey: "thief",
    tags: ["разширена", "нощна роля", "неутрална", "еднократна"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
  little_girl: {
    id: "little_girl",
    gameId: "werewolves",
    nameBg: "Малко момиче",
    shortDescriptionBg: "Разширена ръчна роля за игра на живо с надничане по време на нощта.",
    fullDescriptionBg:
      "Тази роля е създадена за игра на живо с Разказвач и позволява внимателно надничане през нощта. В телефонния режим остава ръчна разширена роля. Ако я включите, Разказвачът трябва предварително да обясни точно как действа.",
    team: "village",
    value: 0,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "little-girl",
    tags: ["разширена", "селяни"],
    secret: true,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["werewolves"],
  },
} as const satisfies Record<string, RoleDefinition>;
