import type { RoleDefinition } from "../shared/types.js";

export const MAFIA_ROLE_DEFINITIONS = {
  civilian: {
    id: "civilian",
    gameId: "mafia",
    nameBg: "Гражданин",
    shortDescriptionBg: "Няма нощно действие. Печели с Града чрез обсъждане и гласуване.",
    fullDescriptionBg:
      "Нямаш нощно действие, затова всичко зависи от разговора и гласа ти. Следи кой сменя алибито си, кой пази някого без причина и кой отклонява масата от важен въпрос. Печелиш с Града, когато цялата Мафия е извън играта.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 24,
    dependencies: [],
    assetKey: "civilian",
    tags: ["основна", "град"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["mafia"],
  },
  mafioso: {
    id: "mafioso",
    gameId: "mafia",
    nameBg: "Мафиот",
    shortDescriptionBg: "Будиш се с Мафията и участваш в избора на нощна жертва.",
    fullDescriptionBg:
      "Будите се заедно, договаряте жертвата и после се връщате на масата като непознати. През деня трябва да пазиш своите, без защитата ти да изглежда очевидна, и да насочиш съмнението към Града.",
    team: "mafia",
    value: -5,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 8,
    dependencies: [],
    assetKey: "mafioso",
    tags: ["основна", "нощна роля", "атакуваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  don: {
    id: "don",
    gameId: "mafia",
    nameBg: "Кръстник",
    shortDescriptionBg: "Води Мафията и може да търси Комисаря.",
    fullDescriptionBg:
      "Играеш с Мафията и всяка нощ можеш да провериш дали избран играч е Комисарят. Трябва да координираш отбора си, без да изглеждаш като човекът, който го води.",
    team: "mafia",
    value: -6,
    nightOrder: 2,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "don",
    tags: ["основна", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  commissioner: {
    id: "commissioner",
    gameId: "mafia",
    nameBg: "Комисар",
    shortDescriptionBg: "Всяка нощ проверява дали избран играч е от Мафията.",
    fullDescriptionBg:
      "Всяка нощ проверяваш един играч и научаваш дали е от Мафията. Използвай резултата внимателно, защото откритият Комисар бързо става нощна цел.",
    team: "village",
    value: 6,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "commissioner",
    tags: ["основна", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  doctor: {
    id: "doctor",
    gameId: "mafia",
    nameBg: "Доктор",
    shortDescriptionBg: "Всяка нощ пази един играч от нощна смърт.",
    fullDescriptionBg:
      "Всяка нощ избираш един играч. Ако тази нощ той трябва да умре, защитата ти го спасява. Дали можеш да пазиш себе си се решава от настройките на стаята.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: true,
    minPlayers: 7,
    maxCopies: 1,
    dependencies: [],
    assetKey: "doctor",
    tags: ["основна", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  detective: {
    id: "detective",
    gameId: "mafia",
    nameBg: "Детектив",
    shortDescriptionBg: "Разследва по-фино от Комисаря според избраните правила.",
    fullDescriptionBg:
      "В свободните игри получаваш допълнителна проверка според настройките на стаята. Събирай резултатите постепенно и ги сравнявай с твърденията на масата, вместо да повтаряш ролята на Комисаря.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "detective",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  bodyguard: {
    id: "bodyguard",
    gameId: "mafia",
    nameBg: "Бодигард",
    shortDescriptionBg: "Пази играч с риск за себе си.",
    fullDescriptionBg:
      "Всяка нощ пазиш друг играч. Ако той бъде нападнат, спасяваш го и поемаш удара вместо него. Затова най-важният ти избор е кого Мафията смята за опасен точно тази нощ.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "bodyguard",
    tags: ["разширена", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  vigilante: {
    id: "vigilante",
    gameId: "mafia",
    nameBg: "Вигиланте",
    shortDescriptionBg: "Градска атакуваща роля, която може да елиминира подозрителен играч.",
    fullDescriptionBg:
      "През нощта можеш да елиминираш подозрителен играч. Грешният изстрел помага на Мафията толкова, колкото правилният помага на Града, затова не стреляй само за да използваш действието си.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vigilante",
    tags: ["разширена", "нощна роля", "атакуваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  medium: {
    id: "medium",
    gameId: "mafia",
    nameBg: "Медиум",
    shortDescriptionBg: "Научава ролята на избран елиминиран играч.",
    fullDescriptionBg:
      "Всяка нощ можеш да избереш елиминиран играч и да научиш ролята, с която е започнал. Не го връщаш в играта, но получаваш следа, която живите може да са пропуснали.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "medium",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  roleblocker: {
    id: "roleblocker",
    gameId: "mafia",
    nameBg: "Блокиращ",
    shortDescriptionBg: "Пречи на избран играч да използва нощното си действие.",
    fullDescriptionBg:
      "Всяка нощ избираш играч и спираш действието му. Можеш да блокираш враг, но можеш и да лишиш Града от важна проверка или защита. Печелиш с Града.",
    team: "village",
    value: 0,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "roleblocker",
    tags: ["разширена", "нощна роля", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lawyer: {
    id: "lawyer",
    gameId: "mafia",
    nameBg: "Адвокат",
    shortDescriptionBg: "Защитава играч от разследване или публично подозрение според правилата.",
    fullDescriptionBg:
      "Всяка нощ прикриваш един играч. Проверка срещу него връща невинен резултат според правилата на стаята. Избери кого да покриеш така, че повтарящото се чисто алиби да не издаде Мафията.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lawyer",
    tags: ["разширена", "нощна роля", "защитна", "мафия"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  informant: {
    id: "informant",
    gameId: "mafia",
    nameBg: "Доносник",
    shortDescriptionBg: "Всяка нощ научава точната роля на избран играч.",
    fullDescriptionBg:
      "Всяка нощ научаваш точната роля на един играч. Използвай информацията, за да намериш опасните за Мафията роли, без да издадеш откъде знаеш.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 11,
    maxCopies: 1,
    dependencies: [],
    assetKey: "informant",
    tags: ["разширена", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  maniac: {
    id: "maniac",
    gameId: "mafia",
    nameBg: "Маниак",
    shortDescriptionBg: "Трета страна, която елиминира през нощта и играе сама.",
    fullDescriptionBg:
      "Не си с Града и не си с Мафията. Всяка нощ можеш да елиминираш играч и печелиш сам, когато останеш единствената заплаха. И двата отбора са твои противници.",
    team: "neutral",
    value: -4,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "maniac",
    tags: ["разширена", "нощна роля", "атакуваща", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
    winConditionBg: "Печели самостоятелно според настройките за трета страна.",
  },
  jester: {
    id: "jester",
    gameId: "mafia",
    nameBg: "Шут",
    shortDescriptionBg: "Иска да бъде елиминиран чрез дневното гласуване.",
    fullDescriptionBg:
      "Печелиш лично, ако масата те елиминира чрез дневно гласуване. Нощна смърт не изпълнява целта ти. Трябва да изглеждаш достатъчно подозрително, без останалите да разберат, че точно това искаш.",
    team: "neutral",
    value: -1,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "jester",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["mafia", "werewolves"],
    winConditionBg: "Печели лично, ако бъде елиминиран чрез дневно гласуване.",
  },
  mafia_mayor: {
    id: "mafia_mayor",
    gameId: "mafia",
    nameBg: "Кмет",
    shortDescriptionBg: "Публична или тайна роля с по-силен глас при равенство.",
    fullDescriptionBg:
      "Според настройките титлата ти е публична или тайна. При равенство твоят глас решава кой напуска играта; във всички други случаи тежи колкото останалите. Използвай авторитета си пестеливо, защото Мафията следи кой води масата.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "град"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lovers: {
    id: "lovers",
    gameId: "mafia",
    nameBg: "Влюбени",
    shortDescriptionBg: "Двама играчи са свързани: смъртта на единия застрашава другия.",
    fullDescriptionBg:
      "Две досиета се връзват с една нишка и от този момент масата вече не брои само отбори. Ако единият падне, другият може да бъде повлечен след него, а при някои настройки двамата гонят отделна победа. Влюбените правят всяко обвинение лично.",
    team: "lovers",
    value: 0,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lovers",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
} as const satisfies Record<string, RoleDefinition>;
