import type { RoleDefinition } from "../shared/types.js";

export const MAFIA_ROLE_DEFINITIONS = {
  civilian: {
    id: "civilian",
    gameId: "mafia",
    nameBg: "Гражданин",
    shortDescriptionBg: "Няма нощно действие. Печели с Града чрез обсъждане и гласуване.",
    fullDescriptionBg:
      "Нямаш досие с тайни, но имаш очи за пукнатини в алибитата. Слушай кой говори като по сценарий, кой пази някого прекалено меко и кой сменя посоката точно когато масата се приближи до истината. Градът печели, когато Мафията изгуби контрол над гласа.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 24,
    dependencies: [],
    assetKey: "civilian",
    tags: ["основна", "град"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["mafia"],
  },
  mafioso: {
    id: "mafioso",
    gameId: "mafia",
    nameBg: "Мафиот",
    shortDescriptionBg: "Будиш се с Мафията и участваш в избора на нощна жертва.",
    fullDescriptionBg:
      "Будите се заедно, договаряте жертвата и после се връщате на масата като хора, които уж нямат общо. През деня задачата ти не е само да оцелееш, а да направиш грешния гражданин убедителен заподозрян. Добър Мафиот лъже малко, но навреме.",
    team: "mafia",
    value: -5,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 8,
    dependencies: [],
    assetKey: "mafioso",
    tags: ["основна", "нощна роля", "атакуваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  don: {
    id: "don",
    gameId: "mafia",
    nameBg: "Кръстник",
    shortDescriptionBg: "Води Мафията и може да търси Комисаря.",
    fullDescriptionBg:
      "Ти държиш тъмната страна на масата събрана. Освен че играеш с Мафията, можеш да търсиш Комисаря и да решиш къде е най-опасната информация. Ако говориш твърде чисто, ще светнеш; ако говориш твърде малко, ще те посочат.",
    team: "mafia",
    value: -6,
    nightOrder: 2,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "don",
    tags: ["основна", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  commissioner: {
    id: "commissioner",
    gameId: "mafia",
    nameBg: "Комисар",
    shortDescriptionBg: "Проверява играч през нощта и търси Мафията.",
    fullDescriptionBg:
      "Всяка нощ отваряш едно досие и търсиш мириса на Мафия. Резултатът зависи от настройките: може да видиш само отбор, а може и точна роля. Не печелиш, като извикаш истината веднага; печелиш, като я внесеш в разговора така, че Градът да я понесе.",
    team: "village",
    value: 6,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "commissioner",
    tags: ["основна", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  doctor: {
    id: "doctor",
    gameId: "mafia",
    nameBg: "Доктор",
    shortDescriptionBg: "Пази един играч от нощното убийство на Мафията.",
    fullDescriptionBg:
      "В града винаги има една врата, пред която линейката пристига навреме. Всяка нощ избираш кого да пазиш; ако Мафията удари там, жертвата оцелява. Дали можеш да пазиш себе си се решава от настройките на стаята, затова чети правилата преди първата нощ.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: true,
    minPlayers: 7,
    maxCopies: 1,
    dependencies: [],
    assetKey: "doctor",
    tags: ["основна", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  detective: {
    id: "detective",
    gameId: "mafia",
    nameBg: "Детектив",
    shortDescriptionBg: "Разследва по-фино от Комисаря според избраните правила.",
    fullDescriptionBg:
      "Детективът не влиза с прожектор, а с бележник. В свободните игри получава допълнителен начин да проверява подозрения или да сравнява следи според настройките. Силен е, когато не се състезава с Комисаря, а допълва неговата линия.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "detective",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  bodyguard: {
    id: "bodyguard",
    gameId: "mafia",
    nameBg: "Бодигард",
    shortDescriptionBg: "Пази играч с риск за себе си.",
    fullDescriptionBg:
      "Избираш чия сянка да пазиш през нощта и приемаш, че куршумът може да смени посоката. Ако атаката падне върху целта ти, можеш да я спасиш, но рискът за теб зависи от настройките. Бодигардът е роля за играчи, които усещат кога някой става прекалено ценен.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "bodyguard",
    tags: ["разширена", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  vigilante: {
    id: "vigilante",
    gameId: "mafia",
    nameBg: "Вигиланте",
    shortDescriptionBg: "Градска атакуваща роля, която може да елиминира подозрителен играч.",
    fullDescriptionBg:
      "Градът ти е дал оръжие, но не и гаранция, че си прав. Можеш да елиминираш подозрителен играч, а грешният изстрел е подарък за Мафията. Вигилантето е силно само когато търпението е по-силно от желанието за геройство.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vigilante",
    tags: ["разширена", "нощна роля", "атакуваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  medium: {
    id: "medium",
    gameId: "mafia",
    nameBg: "Медиум",
    shortDescriptionBg: "Работи с информация от елиминираните играчи.",
    fullDescriptionBg:
      "След като масата загуби човек, ти все още можеш да чуеш ехото му. В игри с мъртъв чат или водещ получаваш ограничена информация от елиминираните според правилата на стаята. Медиумът не връща мъртвите, но може да върне една пропусната следа.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "medium",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  roleblocker: {
    id: "roleblocker",
    gameId: "mafia",
    nameBg: "Блокиращ",
    shortDescriptionBg: "Пречи на избран играч да използва нощното си действие.",
    fullDescriptionBg:
      "Една врата се затваря, един телефон не звъни, едно действие не се случва. Избираш играч и блокираш нощното му действие за тази нощ. Ролята е опасно силна, защото може да спре враг, но може и да отреже най-важния човек на Града.",
    team: "neutral",
    value: 0,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "roleblocker",
    tags: ["разширена", "нощна роля", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lawyer: {
    id: "lawyer",
    gameId: "mafia",
    nameBg: "Адвокат",
    shortDescriptionBg: "Защитава играч от разследване или публично подозрение според правилата.",
    fullDescriptionBg:
      "Адвокатът не доказва невинност; той прави вината трудна за хващане. В свободна Мафия може да обърква проверки или да защитава конкретен играч според настройките. Най-добрата му защита е да изглежда като разум, не като алиби.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lawyer",
    tags: ["разширена", "нощна роля", "защитна", "мафия"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  informant: {
    id: "informant",
    gameId: "mafia",
    nameBg: "Доносник",
    shortDescriptionBg: "Играе с информация и може да обслужва Мафията или собствена цел.",
    fullDescriptionBg:
      "Доносникът живее между истината и удобната версия на истината. Според настройките може да знае част от състава, да подава сигнали или да обърква чуждите линии. На масата е силен, когато никой не е сигурен дали помага или продава информация.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 11,
    maxCopies: 1,
    dependencies: [],
    assetKey: "informant",
    tags: ["разширена", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  maniac: {
    id: "maniac",
    gameId: "mafia",
    nameBg: "Маниак",
    shortDescriptionBg: "Трета страна, която елиминира през нощта и играе сама.",
    fullDescriptionBg:
      "Не си Град и не си Мафия; градът просто е твърде шумен, за да те чуе навреме. Имаш собствена нощна атака и играеш за самостоятелна победа според настройките. Маниакът печели от хаоса, но губи, ако стане твърде очевидната трета следа.",
    team: "neutral",
    value: -4,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "maniac",
    tags: ["разширена", "нощна роля", "атакуваща", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
    winConditionBg: "Печели самостоятелно според настройките за трета страна.",
  },
  jester: {
    id: "jester",
    gameId: "mafia",
    nameBg: "Шут",
    shortDescriptionBg: "Иска да бъде елиминиран чрез дневното гласуване.",
    fullDescriptionBg:
      "Ти си единственият човек на масата, който иска присъдата да падне върху него. Печелиш лично, ако те елиминират чрез дневно гласуване, но нощна смърт не ти върши работа. Шутът трябва да бъде подозрителен точно толкова, че да го изгонят, не толкова, че да го игнорират.",
    team: "neutral",
    value: -1,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "jester",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["mafia"],
    winConditionBg: "Печели лично, ако бъде елиминиран чрез дневно гласуване.",
  },
  mafia_mayor: {
    id: "mafia_mayor",
    gameId: "mafia",
    nameBg: "Кмет",
    shortDescriptionBg: "Публична или тайна роля с по-силен глас при равенство.",
    fullDescriptionBg:
      "Кметът е тежест върху масата, не украшение. Според настройките може да бъде публичен или таен, а при равенство гласът му накланя присъдата. Добър Кмет не бърза да командва; чака момента, в който всички други гласове са заседнали.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "град"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lovers: {
    id: "lovers",
    gameId: "mafia",
    nameBg: "Влюбени",
    shortDescriptionBg: "Двама играчи са свързани: смъртта на единия застрашава другия.",
    fullDescriptionBg:
      "Две досиета се връзват с една нишка и от този момент масата вече не брои само отбори. Ако единият падне, другият може да бъде повлечен след него, а при някои настройки двамата гонят отделна победа. Влюбените правят всяко обвинение лично.",
    team: "lovers",
    value: 0,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lovers",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: true,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
} as const satisfies Record<string, RoleDefinition>;
