import type { RoleDefinition } from "../shared/types.js";

export const MAFIA_ROLE_DEFINITIONS = {
  civilian: {
    id: "civilian",
    gameId: "mafia",
    nameBg: "Гражданин",
    shortDescriptionBg: "Няма нощно действие. Печели с Града чрез обсъждане и гласуване.",
    fullDescriptionBg:
      "Гражданите нямат специална нощна информация. Тяхната сила е в речта, наблюдението и правилното елиминиране на Мафията през деня.",
    team: "village",
    value: 1,
    nightOrder: null,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 24,
    dependencies: [],
    assetKey: "civilian",
    tags: ["основна", "град"],
    secret: true,
    nightAction: false,
    availableInFamilies: ["mafia"],
  },
  mafioso: {
    id: "mafioso",
    gameId: "mafia",
    nameBg: "Мафиот",
    shortDescriptionBg: "Будиш се с Мафията и участваш в избора на нощна жертва.",
    fullDescriptionBg:
      "Мафиотите се познават, координират се през нощта и се опитват през деня да изглеждат като обикновени граждани.",
    team: "mafia",
    value: -5,
    nightOrder: 3,
    isDefaultEnabled: true,
    minPlayers: 4,
    maxCopies: 8,
    dependencies: [],
    assetKey: "mafioso",
    tags: ["основна", "нощна роля", "атакуваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  don: {
    id: "don",
    gameId: "mafia",
    nameBg: "Кръстник",
    shortDescriptionBg: "Води Мафията и може да търси Комисаря.",
    fullDescriptionBg:
      "Кръстникът е лидерът на Мафията. В спортния формат обикновено има отделна проверка за Комисаря и помага на Мафията да насочи стратегията си.",
    team: "mafia",
    value: -6,
    nightOrder: 2,
    isDefaultEnabled: true,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "don",
    tags: ["основна", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  commissioner: {
    id: "commissioner",
    gameId: "mafia",
    nameBg: "Комисар",
    shortDescriptionBg: "Проверява играч през нощта и търси Мафията.",
    fullDescriptionBg:
      "Комисарят избира един играч и получава резултат според настройките: само отбор или точна роля. Информацията е лична и трябва да се използва внимателно.",
    team: "village",
    value: 6,
    nightOrder: 5,
    isDefaultEnabled: true,
    minPlayers: 6,
    maxCopies: 1,
    dependencies: [],
    assetKey: "commissioner",
    tags: ["основна", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  doctor: {
    id: "doctor",
    gameId: "mafia",
    nameBg: "Доктор",
    shortDescriptionBg: "Пази един играч от нощното убийство на Мафията.",
    fullDescriptionBg:
      "Докторът избира играч през нощта. Ако Мафията атакува същия играч, жертвата оцелява. Дали Докторът може да пази себе си се управлява от настройките на стаята.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: true,
    minPlayers: 7,
    maxCopies: 1,
    dependencies: [],
    assetKey: "doctor",
    tags: ["основна", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    availableInFamilies: ["mafia"],
  },
  detective: {
    id: "detective",
    gameId: "mafia",
    nameBg: "Детектив",
    shortDescriptionBg: "Разследва по-фино от Комисаря според избраните правила.",
    fullDescriptionBg:
      "Детективът е допълнителна разследваща роля за свободни игри. Може да проверява подозрителни играчи или да сравнява информация според домашните правила.",
    team: "village",
    value: 5,
    nightOrder: 7,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "detective",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  bodyguard: {
    id: "bodyguard",
    gameId: "mafia",
    nameBg: "Бодигард",
    shortDescriptionBg: "Пази играч с риск за себе си.",
    fullDescriptionBg:
      "Бодигардът избира кого да охранява. При атака може да спаси целта, като поеме последствията според настройките на играта.",
    team: "village",
    value: 4,
    nightOrder: 6,
    isDefaultEnabled: false,
    minPlayers: 9,
    maxCopies: 1,
    dependencies: [],
    assetKey: "bodyguard",
    tags: ["разширена", "нощна роля", "защитна", "град"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  vigilante: {
    id: "vigilante",
    gameId: "mafia",
    nameBg: "Вигиланте",
    shortDescriptionBg: "Градска атакуваща роля, която може да елиминира подозрителен играч.",
    fullDescriptionBg:
      "Вигилантето има опасна сила за Града: може да атакува, но грешен избор помага на Мафията. Подходящо е за по-опитни групи.",
    team: "village",
    value: 3,
    nightOrder: 8,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "vigilante",
    tags: ["разширена", "нощна роля", "атакуваща", "град"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  medium: {
    id: "medium",
    gameId: "mafia",
    nameBg: "Медиум",
    shortDescriptionBg: "Работи с информация от елиминираните играчи.",
    fullDescriptionBg:
      "Медиумът е роля за игри с мъртъв чат или водещ. Може да получава ограничена информация от вече елиминирани играчи според правилата на стаята.",
    team: "village",
    value: 3,
    nightOrder: 9,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "medium",
    tags: ["разширена", "нощна роля", "разследваща", "град"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  roleblocker: {
    id: "roleblocker",
    gameId: "mafia",
    nameBg: "Блокиращ",
    shortDescriptionBg: "Пречи на избран играч да използва нощното си действие.",
    fullDescriptionBg:
      "Блокиращият избира играч и спира неговото нощно действие за тази нощ. Тази роля е силна и може да промени баланса на играта.",
    team: "neutral",
    value: 0,
    nightOrder: 1,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "roleblocker",
    tags: ["разширена", "нощна роля", "неутрална"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lawyer: {
    id: "lawyer",
    gameId: "mafia",
    nameBg: "Адвокат",
    shortDescriptionBg: "Защитава играч от разследване или публично подозрение според правилата.",
    fullDescriptionBg:
      "Адвокатът е социална/защитна роля за свободна Мафия. Най-често обърква проверките или защитава конкретен играч в дневната фаза.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lawyer",
    tags: ["разширена", "нощна роля", "защитна", "мафия"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  informant: {
    id: "informant",
    gameId: "mafia",
    nameBg: "Доносник",
    shortDescriptionBg: "Играе с информация и може да обслужва Мафията или собствена цел.",
    fullDescriptionBg:
      "Доносникът е разширена информационна роля. В зависимост от настройките може да знае част от състава или да дава подвеждащи сигнали.",
    team: "mafia",
    value: -3,
    nightOrder: 4,
    isDefaultEnabled: false,
    minPlayers: 11,
    maxCopies: 1,
    dependencies: [],
    assetKey: "informant",
    tags: ["разширена", "нощна роля", "разследваща", "мафия"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  maniac: {
    id: "maniac",
    gameId: "mafia",
    nameBg: "Маниак",
    shortDescriptionBg: "Трета страна, която елиминира през нощта и играе сама.",
    fullDescriptionBg:
      "Маниакът е независима заплаха. Обикновено има собствена нощна атака и печели, ако остане последната реална сила в града.",
    team: "neutral",
    value: -4,
    nightOrder: 10,
    isDefaultEnabled: false,
    minPlayers: 10,
    maxCopies: 1,
    dependencies: [],
    assetKey: "maniac",
    tags: ["разширена", "нощна роля", "атакуваща", "неутрална"],
    secret: true,
    nightAction: true,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
    winConditionBg: "Печели самостоятелно според настройките за трета страна.",
  },
  jester: {
    id: "jester",
    gameId: "mafia",
    nameBg: "Шут",
    shortDescriptionBg: "Иска да бъде елиминиран чрез дневното гласуване.",
    fullDescriptionBg:
      "Шутът е неутрална роля с лична победа. Целта му е да убеди масата да го елиминира през деня, без да бъде убит през нощта.",
    team: "neutral",
    value: -1,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "jester",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
    winConditionBg: "Печели лично, ако бъде елиминиран чрез дневно гласуване.",
  },
  mafia_mayor: {
    id: "mafia_mayor",
    gameId: "mafia",
    nameBg: "Кмет",
    shortDescriptionBg: "Публична или тайна роля с по-силен глас при равенство.",
    fullDescriptionBg:
      "Кметът в Мафия е configurable роля. Обичайно има решаващ или двоен глас при равни резултати на дневното гласуване.",
    team: "village",
    value: 2,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "mayor",
    tags: ["разширена", "публична", "град"],
    secret: true,
    nightAction: false,
    runtimeStatus: "manual_only",
    advanced: true,
    availableInFamilies: ["mafia"],
  },
  lovers: {
    id: "lovers",
    gameId: "mafia",
    nameBg: "Влюбени",
    shortDescriptionBg: "Двама играчи са свързани: смъртта на единия застрашава другия.",
    fullDescriptionBg:
      "Влюбените са настройка/вариант, не задължително отделна карта. Ако архитектурата на стаята ги включи, двама играчи могат да имат обща съдба или отделна победа.",
    team: "lovers",
    value: 0,
    nightOrder: null,
    isDefaultEnabled: false,
    minPlayers: 8,
    maxCopies: 1,
    dependencies: [],
    assetKey: "lovers",
    tags: ["разширена", "неутрална"],
    secret: true,
    nightAction: false,
    advanced: true,
    availableInFamilies: ["mafia"],
  },
} as const satisfies Record<string, RoleDefinition>;
